name: Docker Pipeline

on :
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'
      
jobs:
  Train:
    name: train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login into the Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building the image of the docker
        run:
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/build1:latest

      - name: Pushing the image to the docker 
        run:
          docker push ${{ secrets.DOCKER_USERNAME }}/build1:latest
        
      - name: Result
        run: |
          echo "The Build job has been successfully finished"
          exit 0
  Test:
    name: test
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Retrieve the docker image from the docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/build1:latest

      - name: Running the docker image and storing the resultant accuracy score
        run: |
          # The docker image is running and result accuracy is stored in score
          score=$(docker run ${{ secrets.DOCKER_USERNAME }}/build1:latest)
          echo "Accuracy score: $score"
          if (( $(echo "$score > 0.35" | bc -l) )); then
            echo "The test is passed as the accuracy score is sufficient and higher than the threshold"
            exit 0
          else
            echo "The test is failed as the accuracy is insufficient and lower than the threshold"
            exit 1
          fi

