name: Action 1 Build and Train Docker Pipeline

on :
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'
      
jobs:
  Train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Image
        run:
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/build1:latest

      - name: Docker Push
        run:
          docker push ${{ secrets.DOCKER_USERNAME }}/build1:latest
        
      - name: Report success
        run: |
          echo "Build job completed successfully"
          exit 0
  Test:
    name: Test
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-assignment:latest

      - name: Run Docker Image Check Score
        run: |
          # Run the docker image and evaluate if threshold is met
          score=$(docker run ${{ secrets.DOCKER_USERNAME }}/cicd-assignment:latest)
          echo "Score: $score"
          if (( $(echo "$score > 0.45" | bc -l) )); then
            echo "Sufficient Accuracy : Test pass"
            exit 0
          else
            echo "Insufficient Accuracy : Test fail"
            exit 1
          fi

