name: Action 1 Build and Train Docker Pipeline

on :
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'
      
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t build1:latest .
          docker tag buid1:latest ${{ env.DOCKER_USERNAME }}/build1:latest
          docker push ${{ env.DOCKER_USERNAME }}/build1:latest

          
